pub enum Port {
    Operate = 1,
    Version = 2,
    Motor = 3,
    DataRate = 4,
    SlowHarvest = 5,
    TemperatureDrop = 6,
    Pid = 7,
    TemperatureEstimate = 8,
    ExternalSensor = 9,
    ExternalTemperature = 10,
    Beep = 0x0b,
    OnOff = 0x0f,
    MotorConfig = 16,
}
